import './globals.css'
import type { Metadata } from 'next'
import { Azeret_Mono } from 'next/font/google'

const fontFamily = Azeret_Mono({ subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-dark'>
      <body className={fontFamily.className}>{children}</body>
    </html>
  )
}
